

	/*HEADER---------------------------------------------------------------------------------------------------------
	|MACRO: 		CLT_SPEC_DRG_LST.SAS
	|
	|PURPOSE: 		
	|
	|INPUT:			
	|
	|LOGIC:         					
	|						
	|OUTPUT			
	|+-----------------------------------------------------------------------------------------------------------------
	|HISTORY: 
	|			    SR 01OCT2008 - Hercules Version  2.1.2.01
	+-----------------------------------------------------------------------------------------------------------HEADER*/

	%MACRO CLT_SPEC_DRG_LST( ADJ_ENGN= ,  PRG_ID = );

	FILENAME EXTCLTL1 "/DATA/%LOWCASE(SAS&SYSMODE.1/HERCULES/&PRG_ID/EXTERNAL_DRUG_LIST/apr_05_2010_client_specific_drug_list_re_1.csv)";
	FILENAME EXTCLTL2 "/DATA/%LOWCASE(SAS&SYSMODE.1/HERCULES/&PRG_ID/EXTERNAL_DRUG_LIST/apr_05_2010_client_specific_drug_list_re_2.csv)";
	FILENAME EXTCLTL3 "/DATA/%LOWCASE(SAS&SYSMODE.1/HERCULES/&PRG_ID/EXTERNAL_DRUG_LIST/apr_05_2010_client_specific_drug_list_re_3.csv)";
		
		%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.);
		%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN.);

		DATA CLIENT_SPECIFIC_DRUG_LIST_1;
			INFILE EXTCLTL1	DSD MISSOVER DELIMITER = ',' FIRSTOBS=2;
			FORMAT 	CLIENT_LEVEL_1 $22.	
					CLIENT_LEVEL_2 $22. 
					CLIENT_LEVEL_3 $22. 
					DRUG_ID        $22.;
			INPUT 	CLIENT_LEVEL_1 $	
					CLIENT_LEVEL_2 $ 
					CLIENT_LEVEL_3 $ 
					DRUG_ID_TYPE_CD 
					DRUG_ID $;
		RUN;
		DATA CLIENT_SPECIFIC_DRUG_LIST_2;
			INFILE EXTCLTL2	DSD MISSOVER DELIMITER = ',' FIRSTOBS=2;
			FORMAT 	CLIENT_LEVEL_1 $22.	
					CLIENT_LEVEL_2 $22. 
					CLIENT_LEVEL_3 $22. 
					DRUG_ID        $22.;
			INPUT 	CLIENT_LEVEL_1 $	
					CLIENT_LEVEL_2 $ 
					CLIENT_LEVEL_3 $ 
					DRUG_ID_TYPE_CD 
					DRUG_ID $;
		RUN;
		DATA CLIENT_SPECIFIC_DRUG_LIST_3;
			INFILE EXTCLTL3	DSD MISSOVER DELIMITER = ',' FIRSTOBS=2;
			FORMAT 	CLIENT_LEVEL_1 $22.	
					CLIENT_LEVEL_2 $22. 
					CLIENT_LEVEL_3 $22. 
					DRUG_ID        $22.;
			INPUT 	CLIENT_LEVEL_1 $	
					CLIENT_LEVEL_2 $ 
					CLIENT_LEVEL_3 $ 
					DRUG_ID_TYPE_CD 
					DRUG_ID $;
		RUN;
		DATA CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.;
	    SET CLIENT_SPECIFIC_DRUG_LIST_1 CLIENT_SPECIFIC_DRUG_LIST_2 CLIENT_SPECIFIC_DRUG_LIST_3;
	  RUN;

		PROC SQL;
			CREATE TABLE CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN. AS
			 SELECT 	 CLIENT_LEVEL_1	
						,CLIENT_LEVEL_2	
						,CLIENT_LEVEL_3 
						,DRUG_ID_TYPE_CD 
						,DRUG_ID 
		                ,INPUT(SUBSTR(DRUG_ID,1,14),14.) AS DRUG_PRODUCT_NDC_ID
		                ,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,01,2),'  ') 
		                                               ELSE '  '
		                 END AS GPI_GROUP
		                ,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,03,2),'  ') 
		                                               ELSE '  '
		                 END AS GPI_CLASS
		                ,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,05,2),'  ') 
		                                               ELSE '  '
		                 END AS GPI_SUBCLASS
						,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,07,2),'  ')
		                                               ELSE '  '
		                 END AS GPI_NAME
						,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,09,2),'  ') 
		                                               ELSE '  '
		                 END AS GPI_NAME_EXTENSION
						,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,11,2),'  ') 
		                                               ELSE '  '
		                 END AS GPI_FORM
						,CASE WHEN DRUG_ID_TYPE_CD = 1 THEN COALESCE(SUBSTR(DRUG_ID,13,2),'  ')
		                                               ELSE '  '
		                 END AS GPI_STRENGTH
			FROM CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.;
		QUIT;

		PROC SQL;
			CREATE TABLE CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN. AS
			SELECT A.*,
			       B.DRUG_NDC_ID,
				   B.NHU_TYPE_CD
			FROM  CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN. A
			     ,CLAIMSA.TDRUG1 B
			WHERE A.DRUG_ID_TYPE_CD = 3
			  AND A.DRUG_PRODUCT_NDC_ID =B.DRUG_NDC_ID;
		QUIT;

		DATA &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.;
			SET CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.;
		RUN;
	
		PROC SQL NOPRINT;
			CREATE TABLE &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN. AS
		 	SELECT DISTINCT A.*, B.DRUG_GID
		 	FROM &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN. A,
	         &DSS_CLIN..V_DRUG_DENORM B
			WHERE A.DRUG_NDC_ID = INPUT(B.NDC_CODE,20.) AND B.DRUG_VLD_FLG = 'Y';
		QUIT;
		%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.);


		PROC SQL NOPRINT;
			SELECT 	COUNT(DRUG_NDC_ID)
			INTO	:COUNT_MISSING_GIDS
			FROM &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN.
			WHERE DRUG_GID IS NULL;
		QUIT;


		%IF &COUNT_MISSING_GIDS > 0 %THEN %DO;
			FILENAME MYMAIL EMAIL 'QCPAP020@TSTSAS1';
		   		DATA _NULL_;
		     		FILE MYMAIL
		         	TO=(&EMAIL_USR)
		         	SUBJECT="CLIENT SPECIFIC EXTERNAL DRUG LIST" ;
					PUT 'HI,' ;
		     		PUT / "THIS IS AN AUTOMATICALLY GENERATED MESSAGE TO INFORM YOU THAT DRUG_GIDS FOR %LEFT(%STR(&COUNT_MISSING_GIDS.)) NDCS ARE NOT AVAILABLE FOR &PRG_ID FOR &ADJ_ENGN ADJUCICATION";
					PUT / 'PLEASE LET US KNOW OF ANY QUESTIONS.';
		    		PUT / 'THANKS,';
		     		PUT / 'HERCULES PRODUCTION SUPPORT';
		   		RUN;
		%END;

		%IF &ADJ_ENGN = RX %THEN %DO;

			%LET CARRIER_FIELD = CLIENT_LEVEL_1;

		%END;

		%IF &ADJ_ENGN = RE %THEN %DO;

			%LET CARRIER_FIELD = CLIENT_LEVEL_2;

		%END;

		PROC SQL;
			CREATE TABLE &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN. AS
			SELECT DISTINCT A.*, B.CLIENT_ID AS QL_CLIENT_ID
			FROM &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN. A
			LEFT JOIN
			     &CLAIMSA..TCLIENT1 B
			ON TRIM(LEFT(A.&CARRIER_FIELD.)) = TRIM(LEFT(SUBSTR(B.CLIENT_CD,2)));
		QUIT;
		%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN.);

		PROC SQL;
			CONNECT TO ORACLE(PATH = &GOLD.);
			EXECUTE
			(
			CREATE TABLE &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN. AS
			SELECT A.*
			FROM &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN. A
			LEFT JOIN
			     &ORA_TMP..EXT_CLIENT_DRUG_TABLE_&ADJ_ENGN.  B
			ON 		A.CLIENT_LEVEL_1 = B.CLIENT_LEVEL_1 
			    AND A.CLIENT_LEVEL_2 = B.CLIENT_LEVEL_2
				AND A.CLIENT_LEVEL_3 = B.CLIENT_LEVEL_3
		    	AND A.DRUG_GID = B.DRUG_GID
		    WHERE (B.DRUG_GID IS NULL AND
		           B.CLIENT_LEVEL_1 IS NULL)
	        )BY ORACLE;
			DISCONNECT FROM ORACLE;
		QUIT;
		%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST_&ADJ_ENGN.);

		PROC SQL;
			CONNECT TO ORACLE(PATH = &GOLD.);
			EXECUTE
			(
			INSERT INTO &ORA_TMP..EXT_CLIENT_DRUG_TABLE_&ADJ_ENGN. 
				(PROGRAM_ID, QL_CLIENT_ID, 
	             CLIENT_LEVEL_1, CLIENT_LEVEL_2, CLIENT_LEVEL_3,
				 DRUG_GID, GPI_GROUP, GPI_CLASS,
				 EFFECTIVE_DT, EXPIRATION_DT, 
			     HSC_USR_ID, HSC_TS, HSU_USR_ID, HSU_TS)
			SELECT 
				 &PRG_ID., QL_CLIENT_ID,
	             CLIENT_LEVEL_1, CLIENT_LEVEL_2, CLIENT_LEVEL_3,
				 DRUG_GID, GPI_GROUP, GPI_CLASS,
				 SYSDATE, '9999-12-31', 
				 %BQUOTE('&USER.'), SYSDATE,  %BQUOTE('&USER.'), SYSDATE
			FROM 
				&ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN.
	        )BY ORACLE;
			DISCONNECT FROM ORACLE;
		QUIT;

	    %SET_ERROR_FL;

		%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..CLIENT_SPECIFIC_DRUG_LIST2_&ADJ_ENGN.);
	
	%MEND CLT_SPEC_DRG_LST;


