libname TMP79 db2 DSN=&UDBSPRP SCHEMA=TMP79 DEFER=YES;

libname SYSCAT db2 DSN=&UDBSPRP SCHEMA=SYSCAT DEFER=YES;

PROC SQL;
     CONNECT TO DB2 (DSN=&UDBSPRP);
     CREATE TABLE TMP106.T_456_1_ADHOC AS
     SELECT 1 AS DRUG_GROUP_SEQ_NB,
            1 AS DRUG_SUB_GRP_SEQ_NB,
            DRUG_NDC_ID,
            NHU_TYPE_CD
             FROM CONNECTION TO DB2
     (SELECT *
       FROM CLAIMSA.TDRUG1
       WHERE GENERIC_AVAIL_IN=1
       AND DRUG_BRAND_CD='B');
     DISCONNECT FROM DB2; QUIT;


   PROC SQL;
     CONNECT TO DB2 (DSN=&UDBSPRP);
     CREATE TABLE YOUNG_NDCS_CNT AS
     SELECT *  FROM CONNECTION TO DB2
     (SELECT COUNT (*) AS CNT
       FROM CLAIMSA.TDRUG1);
     DISCONNECT FROM DB2; QUIT;


 PROC SQL;
     CREATE TABLE TMP106.T_456_1_RVW_DATES AS
      select * from TMP106.T_424_1_RVW_DATES; QUIT;
