
%MACRO EXCLUDE_PARTICIPANTS_72;

OPTIONS SYMBOLGEN MPRINT MLOGIC MLOGICNEST;

LIBNAME PRCT_EXC "/DATA/sas&sysmode.1/hercules/participant_exclusions";

DATA PRCT_EXC.PARTICIPANTS_TO_EXCLUDE;
INFILE "/DATA/sas&sysmode.1/hercules/participant_exclusions/participant_exclusion_72.csv" DSD MISSOVER DELIMITER = ',' FIRSTOBS=2;;
INPUT QL_BENEFICIARY_ID;                
RUN;


PROC SQL;
UPDATE DATA_PND.T_&INITIATIVE_ID._&PHASE_SEQ_NB._1 A
SET DATA_QUALITY_CD = 3
WHERE A.RECIPIENT_ID in
		(select ql_beneficiary_id from PRCT_EXC.PARTICIPANTS_TO_EXCLUDE);
QUIT;

%MEND EXCLUDE_PARTICIPANTS_72;


