/*HEADER---------------------------------------------------------------------------------------------------------
|MACRO: 		PARTICIPANT_EXCLUSIONS.SAS
|
|PURPOSE: 		
|
|INPUT:			
|
|LOGIC:         					
|						
|OUTPUT:		
|+-----------------------------------------------------------------------------------------------------------------
|HISTORY: 
|			    SR 01OCT2008 - Hercules Version  2.1.2.01
+-----------------------------------------------------------------------------------------------------------HEADER*/

%MACRO PARTICIPANT_EXCLUSIONS_TST(TBL_NAME_IN = );

LIBNAME PRCT_EXC "/DATA/%LOWCASE(SAS&SYSMODE.1/HERCULES/PARTICIPANT_EXCLUSIONS)";

PROC SQL;
	SELECT COUNT(*) INTO :PT_EXC_CNT
	FROM PRCT_EXC.PARTICIPANT_EXCLUSION
    WHERE PROGRAM_ID = &PROGRAM_ID.
	  AND TODAY() BETWEEN EFFECTIVE_DT AND EXPIRATION_DT;
QUIT;

%IF &PT_EXC_CNT > 0 %THEN %DO;

	%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..PARTICIPANT_EXCLUSIONS_&INITIATIVE_ID._&ADJ_ENGINE.);
	PROC SQL;
		CREATE TABLE &ORA_TMP..PARTICIPANT_EXCLUSIONS_&INITIATIVE_ID._&ADJ_ENGINE. AS
		SELECT * FROM PRCT_EXC.PARTICIPANT_EXCLUSION
	    WHERE PROGRAM_ID = &PROGRAM_ID.
		  AND TODAY() BETWEEN EFFECTIVE_DT AND EXPIRATION_DT;

	QUIT;

/* 22DEC2008 - SY -  MODIFIED THE SQL. DELETED THE CONNECTION TO ORACLE */

	PROC SQL;
			DELETE FROM &TBL_NAME_IN. A
			WHERE EXISTS ( SELECT 'X'
			               FROM &ORA_TMP..PARTICIPANT_EXCLUSIONS_&INITIATIVE_ID._&ADJ_ENGINE. B
			               WHERE A.MBR_GID = B.MBR_GID);
	QUIT;

/* 22DEC2008 - SY -  MODIFIED THE SQL. DELETED THE CONNECTION TO ORACLE */

	PROC SQL;
			DELETE FROM &TBL_NAME_IN. A
			WHERE EXISTS ( SELECT 'X'
			               FROM &ORA_TMP..PARTICIPANT_EXCLUSIONS_&INITIATIVE_ID._&ADJ_ENGINE. B
			               WHERE TRIM(LEFT(TRIM(RIGHT(A.PT_BENEFICIARY_ID)))) = TRIM(LEFT(TRIM(RIGHT(B.QL_BENEFICIARY_ID)))));
	QUIT;

/* 22DEC2008 - SY -  MODIFIED THE SQL. DELETED THE CONNECTION TO ORACLE */

	PROC SQL;
			DELETE FROM &TBL_NAME_IN. A
			WHERE EXISTS ( SELECT 'X'
			               FROM &ORA_TMP..PARTICIPANT_EXCLUSIONS_&INITIATIVE_ID._&ADJ_ENGINE. B
			               WHERE TRIM(LEFT(TRIM(RIGHT(A.MBR_ID)))) = TRIM(LEFT(TRIM(RIGHT(B.MBR_ID)))));
	QUIT;

	%DROP_ORACLE_TABLE(TBL_NAME = &ORA_TMP..PARTICIPANT_EXCLUSIONS_&INITIATIVE_ID._&ADJ_ENGINE.);

%END;

%MEND PARTICIPANT_EXCLUSIONS_TST;



